steps:

# build aps
- id: 'tf plan'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      gcloud components update kubectl
      kubectl apply -f release/kubernetes-manifests.yaml